### ISSUE TITLE
ButtonVariant not exported and therefore not useable

### ISSUE THREAD

**Issue by bobbonius** [TicketSwap/solar#1042]
## Problem description
When using a `<Button />` component and using the `variant` property, the `ButtonVariant` enum is expected to be used. For example `ButtonVariant.primary`. At the moment it's not possible to import the `ButtonVariant` as it's not being exported. 

## Steps to reproduce
Steps to reproduce the behavior.

1. Scaffold a nextjs / create-react-app project
2. `yarn add @ticketswap/solar`
3. `import { ButtonVariant } from "@ticketswap/solar"`

## Expected behaviour
Be able to import the `ButtonVariant` enum and use the variants inside :)

## Additional context
[Screenshot](https://prnt.sc/whjb9o)

**Comment by glenngijsberts** [comment]
@bobbonius It took a while but this is finally fixed :)

**Comment by bobbonius** [comment]
@glenngijsberts 👍
