### ISSUE TITLE
Introduce color swatches

### ISSUE THREAD

**Issue by glenngijsberts** [TicketSwap/solar#1176]
## Improvement description
Would be nice to display our colors in Storybook.

Something like this:

<img width="372" alt="Schermafbeelding 2021-09-01 om 15 00 21" src="https://user-images.githubusercontent.com/14276144/131675541-72ad38ea-07e8-4ac0-8808-c218cb0d041c.png">

**Comment by bobbonius** [comment]
This is live: https://ticketswap.github.io/solar/?path=/story/design-tokens-colors-earth--earth
