### ISSUE TITLE
Investigate if Dialog component is cancelling all async tasks on unmount

### ISSUE THREAD

**Issue by diogoredin** [TicketSwap/solar#1225]
## Problem description
The Dialog component seems to have a memory leak. Most event handlers are removed when the component is unmounted but [useTransition](https://github.com/TicketSwap/solar/blob/main/src/hooks/useTransition.ts) doesn't seem to.

<img width="957" alt="Screenshot 2021-10-21 at 17 41 08" src="https://user-images.githubusercontent.com/1096800/138312695-c19cf1f9-962f-4d20-9de9-eac560b27bb4.png">

## Steps to reproduce
1. Go to Sirius
2. Run any test suite where a Dialog is used multiple times (and hence mounted and unmounted multiple times);

## Expected behaviour
All async tasks should be cancelled upon unmounting, the component shouldn't leak.

## Additional context
I believe we don't see this memory leak in Solar tests because these are fairly fast (we don't do any data mocks, loading states etc.), which would otherwise give time for these async tasks to try to update the state of unmounted instances.

**Comment by glenngijsberts** [comment]
`Go to Sirius` If this is the first step I would say this belongs in sirius, or is this really a solar issue? If it's a solar issue, we should make this re-produceable in Solar. If we think about "open source" then non-TS people won't know what Sirius is, so they can't reproduce.
