### ISSUE TITLE
Add a TinyText component

### ISSUE THREAD

**Issue by Marruk** [TicketSwap/solar#1377]
## Feature description
In designs (on Desktop) we want to have the option for a smaller text size than the SmallText, for example in dialog subtitles:
![Screenshot 2022-02-22 at 11 57 12](https://user-images.githubusercontent.com/6670305/155118624-0885e9af-08bb-4b8c-a47c-027ec02952de.JPG)

At the moment there are already quite some places where we use this text size, but it's not an official component yet.

The text size would be `0.875rem` (14px) with a default line height of `1.5` as with all other text styles. On mobile the text size shouldn't change (14px is as low as we want to go).

**Comment by Emacdyz** [comment]
Will pick this up
