### ISSUE TITLE
Date picker: month selector with TimeFrame future

### ISSUE THREAD

**Issue by Emacdyz** [TicketSwap/solar#1534]
## Improvement description
The date picker with a `future` timeFrame is showing all months of the year, even if those months are in the past. For example, if you are in July 2022 and open the month select input, it will show all the months of the past for that year. The dates will be disabled though. 

## Expected behaviour
Should only show the month that are available in that year, and all months if another year. Probably the same happens when the TimeFrame is `past`

## Additional context
<img width="517" alt="Screenshot 2022-07-12 at 13 56 57" src="https://user-images.githubusercontent.com/34305012/178484599-e1d1b554-2c89-4260-b9e0-4d19428bfdae.png">
<img width="526" alt="Screenshot 2022-07-12 at 13 56 48" src="https://user-images.githubusercontent.com/34305012/178484611-d04f0197-02f8-41e7-adaa-e97cc7dfad9c.png">

**Comment by Marruk** [comment]
I'm not too sure about this. My assumption is that if you want to go to January 2023 you start by selecting the month and then the year. If the actual dates are disabled it would be fine for me to leave it like this.
