### ISSUE TITLE
Implement color Nova in the project

### ISSUE THREAD

**Issue by glenngijsberts** [TicketSwap/solar#870]
In a recent PR (https://github.com/TicketSwap/solar/pull/864) we introduced the color `Nova`, which is white. Let's make a PR to replace all white colors with `Nova`.

**Comment by Roohn** [comment]
@glenngijsberts I think this is already done, also with project Eclipse? 🌑

**Comment by glenngijsberts** [comment]
@Roohn Yes! I will close it :)
