### ISSUE TITLE
Button icon and label doesn't seem to be aligned in the center

### ISSUE THREAD

**Issue by glenngijsberts** [TicketSwap/solar#970]
![image](https://user-images.githubusercontent.com/22071649/95444137-c49a7f00-095d-11eb-8e54-1a32609bbb19.png)
The icon and text doesn't seem to be centered 🧐

_Originally posted by @Roohn in https://github.com/TicketSwap/sirius/pull/3514#issuecomment-705465827_

**Comment by Roohn** [comment]
This has been fixed when implementing the new buttons
